Retrospective/Controllers/EstimationController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace Safeer2.UI.Controllers
{
    public class EstimationController : Controller
    {
      public  static Dictionary<string, string> AgileTeamWeights = new Dictionary<string, string>() {
          { "Ali","80" },
          { "Amir", "80" },
          { "Ahmed","80" },
          { "Waad", "80" },
          { "Keerthi","80" },
          { "Mallesh", "80" },
          { "Asif","80" },
          { "Sarah", "80" },
          { "Amjad","80" },
          { "Alhanouf", "80" },
          { "Bashyer","80" },
          { "Abeer", "80" },
          { "Ala","80" }
      };
        // GET: Retrospective
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitWeight(string name,string weight)
        {
            if (AgileTeamWeights.ContainsKey(name))
            {
                AgileTeamWeights.Remove(name);
            }
            AgileTeamWeights.Add(name, weight);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        public ActionResult GetWeight()
        {
            return Json(AgileTeamWeights,JsonRequestBehavior.AllowGet);
        }
    }
}

Retrospective/Controllers/VotingController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace Safeer2.UI.Controllers
{
    public class VotingController : Controller
    {
      public  static Dictionary<string, string> AgileTeamVoting = new Dictionary<string, string>() {
          { "Ali","11" },
          { "Amir", "11" },
          { "Ahmed","11" },
          { "Waad", "11" },
          { "Keerthi","11" },
          { "Mallesh", "11" },
          { "Asif","11" },
          { "Sarah", "11" },
          { "Amjad","11" },
          { "Alhanouf", "11" },
          { "Bashyer","11" },
          { "Abeer", "11" },
          { "Ala","11" },
          { "Average","0.0" },

      };
        // GET: Retrospective
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitVoting(string name,string Voting)
        {
            if (AgileTeamVoting.ContainsKey(name))
            {
                AgileTeamVoting.Remove(name);
            }
            AgileTeamVoting.Add(name, Voting);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        public ActionResult GetVoting()
        {
            var total = 0.0;
            int count = 0;
            foreach (var item in AgileTeamVoting)
            {
                if (item.Key != "Average")
                {
                    var selectedValue = 0.0;
                    double.TryParse(item.Value, out selectedValue);
                    if (selectedValue == 11 || selectedValue == 0)
                        selectedValue = 0;
                    else
                    {
                        count++;
                        total += selectedValue;
                    }
                }
            }
            
            var average = count == 0 ? 0 :total /count;
            AgileTeamVoting["Average"] =Math.Round(average,2).ToString();
            return Json(AgileTeamVoting, JsonRequestBehavior.AllowGet);
        }
    }
}

Retrospective/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Retrospective Tools", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Members Estimation", "Index", "Estimation")</li>
                    <li>@Html.ActionLink("Members Voting", "Index", "Voting")</li>
                    <li> <a href="/SaveExcel/index">Save Excel to DB</a></li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>